services:
  - type: web
    name: world-chat
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BOT_TOKEN
        value: 8672346594:AAE9Q-6m8E_CkrLtF8mQ3Jf7bWfMNmLcKSk
      - key: BOT_USERNAME
        value: herrmeesagentbot
      - key: ADMIN_PASS
        value: admin2011
      - key: VERIFY_URL
        value: https://hambot-six.vercel.app